// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdtdedvheegfjatqwegl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkdGRlZHZoZWVnZmphdHF3ZWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MDM5MTgsImV4cCI6MjA3NDk3OTkxOH0.6mRKLL0P-BPfg9j5Jjj8_D8t7lg7n3z8D_ojZt0z_qQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});